task :default do
  index = File.open("index.html", "wb")

  FileList["*/"].gsub(/\/$/, "").each do |name|
    File.write "#{name}/index.html", <<HTML
<main></main>
<script type="module">
  import init from './pkg/#{name}.js';
  init();
</script>
HTML
    sh "cd #{name} && wasm-pack build --target web"

    index << <<HTML
<h3><a href="./#{name}/index.html">#{name}</a></h3>
HTML
  end

  # sh "wasm-opt -O4 -o jfb/pkg/jfb_bg.wasm jfb/pkg/jfb_bg.wasm"
end
