task :default do
  index = File.open("index.html", "wb")

  FileList["*/"].gsub(/\/$/, "").each do |name|
    File.write "#{name}/index.html", <<HTML
<main></main>
<script type="module">
  import init, { start } from './pkg/#{name}.js';
  init().then(() => start());
</script>
HTML
    sh "cd #{name} && wasm-pack build --target web"

    index << <<HTML
<h3><a href="./#{name}/index.html">#{name}</a></h3>
HTML
  end
end
