name: Build

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, nightly, 1.31.0]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run: cargo build --verbose
      - run: rake
        working-directory: examples
      - run: cargo test --verbose
      - run: yarn install
        working-directory: tests
      - run: yarn test
        working-directory: tests
      - run: cargo clippy
        continue-on-error: true
